apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
  labels:
   app: cache
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 1
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redislabs/rejson:latest
        ports:
        - containerPort: 6379
          name: cache
        resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector:
    app: cache
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
