apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3worker-deployment
  labels:
    app: s3worker
    tier: middle
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      app: s3worker
      tier: middle
  template:
    metadata:
      labels:
        app: s3worker
        tier: middle
    spec:
      containers:
        - name: s3worker
          image: vikrammvk/s3uploader:latest
          resources:
            requests:
              memory: "40Mi"
              cpu: "40m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 5001
              hostPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: s3worker-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: s3worker
    tier: middle
spec:
  type: LoadBalancer
  selector:
    app: s3worker
    tier: middle
  ports:
  - port: 30002
    targetPort: 5001
    nodePort: 30002

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-s3worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: s3worker-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 25Mi